// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozeNVuYn5HCkSBdIMNuLN8qNMdfewk_Y',
    appId: '1:920527254707:web:b41b2de33c8d59f0beacc6',
    messagingSenderId: '920527254707',
    projectId: 'mapper-b6ecb',
    authDomain: 'mapper-b6ecb.firebaseapp.com',
    storageBucket: 'mapper-b6ecb.firebasestorage.app',
    measurementId: 'G-2D5ZNDVZHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluMQWYf0v3u44mXmj8SI12zgI20ePzfs',
    appId: '1:920527254707:android:8776b839088ed9fcbeacc6',
    messagingSenderId: '920527254707',
    projectId: 'mapper-b6ecb',
    storageBucket: 'mapper-b6ecb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEkVW1sUsVKe8GkkPXDIzQRZG11dJz4o',
    appId: '1:920527254707:ios:e15084b098366d1bbeacc6',
    messagingSenderId: '920527254707',
    projectId: 'mapper-b6ecb',
    storageBucket: 'mapper-b6ecb.firebasestorage.app',
    iosBundleId: 'com.example.geminiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEkVW1sUsVKe8GkkPXDIzQRZG11dJz4o',
    appId: '1:920527254707:ios:e15084b098366d1bbeacc6',
    messagingSenderId: '920527254707',
    projectId: 'mapper-b6ecb',
    storageBucket: 'mapper-b6ecb.firebasestorage.app',
    iosBundleId: 'com.example.geminiTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCozeNVuYn5HCkSBdIMNuLN8qNMdfewk_Y',
    appId: '1:920527254707:web:fcc7f75b8b13e024beacc6',
    messagingSenderId: '920527254707',
    projectId: 'mapper-b6ecb',
    authDomain: 'mapper-b6ecb.firebaseapp.com',
    storageBucket: 'mapper-b6ecb.firebasestorage.app',
    measurementId: 'G-6N7ZKYJ9VS',
  );
}
